package shared.FileSharerServer;


/**
* FileSharerServer/FileSharerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharerIDL.idl
* Quarta-feira, 9 de Outubro de 2019 21h47min02s BRT
*/

public abstract class FileSharerPOA extends org.omg.PortableServer.Servant
 implements FileSharerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("updateRemoteFiles", new java.lang.Integer (0));
    _methods.put ("getFilesFromRemote", new java.lang.Integer (1));
    _methods.put ("getOwnerOfFile", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FileSharerServer/FileSharer/updateRemoteFiles
       {
         String clientUsername = in.read_string ();
         String files[] = StringListHelper.read (in);
         this.updateRemoteFiles (clientUsername, files);
         out = $rh.createReply();
         break;
       }

       case 1:  // FileSharerServer/FileSharer/getFilesFromRemote
       {
         String clientUsername = in.read_string ();
         String $result[] = null;
         $result = this.getFilesFromRemote (clientUsername);
         out = $rh.createReply();
         StringListHelper.write (out, $result);
         break;
       }

       case 2:  // FileSharerServer/FileSharer/getOwnerOfFile
       {
         String fileName = in.read_string ();
         String $result = null;
         $result = this.getOwnerOfFile (fileName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FileSharerServer/FileSharer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileSharer _this() 
  {
    return FileSharerHelper.narrow(
    super._this_object());
  }

  public FileSharer _this(org.omg.CORBA.ORB orb) 
  {
    return FileSharerHelper.narrow(
    super._this_object(orb));
  }


} // class FileSharerPOA
