package shared.FileSharerServer;

/**
* FileSharerServer/FileSharerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharerIDL.idl
* Quarta-feira, 9 de Outubro de 2019 19h21min58s BRT
*/

public final class FileSharerHolder implements org.omg.CORBA.portable.Streamable
{
  public FileSharer value = null;

  public FileSharerHolder ()
  {
  }

  public FileSharerHolder (FileSharer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileSharerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileSharerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileSharerHelper.type ();
  }

}
