package shared.FileSharerServer;


/**
* FileSharerServer/FileSharerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharerIDL.idl
* Quarta-feira, 9 de Outubro de 2019 16h49min44s BRT
*/

abstract public class FileSharerHelper
{
  private static String  _id = "IDL:FileSharerServer/FileSharer:1.0";

  public static void insert (org.omg.CORBA.Any a, FileSharer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FileSharer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FileSharerHelper.id (), "FileSharer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FileSharer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FileSharerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FileSharer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FileSharer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileSharer)
      return (FileSharer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _FileSharerStub stub = new _FileSharerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FileSharer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileSharer)
      return (FileSharer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _FileSharerStub stub = new _FileSharerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
