package shared.FileSharerServer;


/**
* FileSharerServer/FileSharer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharerIDL.idl
* Quarta-feira, 9 de Outubro de 2019 21h47min02s BRT
*/

public interface FileSharer extends FileSharerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileSharer
