package util.Matematica;


/**
* Matematica/Calculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatIDL.idl
* Quinta-feira, 26 de Setembro de 2019 15h40min41s BRT
*/

public interface Calculadora extends CalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculadora
