package util.Matematica;


/**
* Matematica/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatIDL.idl
* Quinta-feira, 26 de Setembro de 2019 15h40min41s BRT
*/

public interface CalculadoraOperations 
{
  float soma (float arg1, float arg2);
  float divisao (float arg1, float arg2);
} // interface CalculadoraOperations
