package shared.FileSharer;


/**
* FileSharer/ByteArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharerIDL.idl
* Domingo, 13 de Outubro de 2019 21h52min07s BRT
*/

public final class ByteArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public ByteArrayHolder ()
  {
  }

  public ByteArrayHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ByteArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ByteArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ByteArrayHelper.type ();
  }

}
