package shared.FileSharer;


/**
* FileSharer/P2P.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharerIDL.idl
* Domingo, 13 de Outubro de 2019 18h54min06s BRT
*/

public interface P2P extends P2POperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface P2P
