package shared.FileSharer;


/**
* FileSharer/P2PHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharerIDL.idl
* Domingo, 13 de Outubro de 2019 18h54min06s BRT
*/

abstract public class P2PHelper
{
  private static String  _id = "IDL:FileSharer/P2P:1.0";

  public static void insert (org.omg.CORBA.Any a, P2P that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static P2P extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (P2PHelper.id (), "P2P");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static P2P read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_P2PStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, P2P value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static P2P narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof P2P)
      return (P2P)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _P2PStub stub = new _P2PStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static P2P unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof P2P)
      return (P2P)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _P2PStub stub = new _P2PStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
