package shared.FileSharer;

/**
* FileSharer/P2PHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharerIDL.idl
* Domingo, 13 de Outubro de 2019 18h54min06s BRT
*/

public final class P2PHolder implements org.omg.CORBA.portable.Streamable
{
  public P2P value = null;

  public P2PHolder ()
  {
  }

  public P2PHolder (P2P initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = P2PHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    P2PHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return P2PHelper.type ();
  }

}
