package shared.FileSharer;


/**
* FileSharer/P2POperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharerIDL.idl
* Domingo, 13 de Outubro de 2019 21h52min07s BRT
*/

public interface P2POperations 
{
  byte[] downloadFile (String fileName);
} // interface P2POperations
