package shared.FileSharer;


/**
* FileSharer/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharerIDL.idl
* Domingo, 13 de Outubro de 2019 21h52min07s BRT
*/

public interface ServerOperations 
{
  void updateRemoteFiles (String clientUsername, String[] files);
  String[] getFilesFromRemote (String clientUsername, String search);
  String getOwnerOfFile (String fileName);
} // interface ServerOperations
