package shared.FileSharer;


/**
* FileSharer/ServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharerIDL.idl
* Domingo, 13 de Outubro de 2019 21h52min07s BRT
*/

public abstract class ServerPOA extends org.omg.PortableServer.Servant
 implements ServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("updateRemoteFiles", new java.lang.Integer (0));
    _methods.put ("getFilesFromRemote", new java.lang.Integer (1));
    _methods.put ("getOwnerOfFile", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FileSharer/Server/updateRemoteFiles
       {
         String clientUsername = in.read_string ();
         String files[] = StringArrayHelper.read (in);
         this.updateRemoteFiles (clientUsername, files);
         out = $rh.createReply();
         break;
       }

       case 1:  // FileSharer/Server/getFilesFromRemote
       {
         String clientUsername = in.read_string ();
         String search = in.read_string ();
         String $result[] = null;
         $result = this.getFilesFromRemote (clientUsername, search);
         out = $rh.createReply();
         StringArrayHelper.write (out, $result);
         break;
       }

       case 2:  // FileSharer/Server/getOwnerOfFile
       {
         String fileName = in.read_string ();
         String $result = null;
         $result = this.getOwnerOfFile (fileName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FileSharer/Server:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Server _this() 
  {
    return ServerHelper.narrow(
    super._this_object());
  }

  public Server _this(org.omg.CORBA.ORB orb) 
  {
    return ServerHelper.narrow(
    super._this_object(orb));
  }


} // class ServerPOA
