package shared.FileSharer;


/**
* FileSharer/StringArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSharerIDL.idl
* Domingo, 13 de Outubro de 2019 21h52min07s BRT
*/

public final class StringArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public StringArrayHolder ()
  {
  }

  public StringArrayHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringArrayHelper.type ();
  }

}
